# Generated by Django 4.2.6 on 2023-10-05 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deadline",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 12, 16, 53, 50, 471321)
                    ),
                ),
                ("is_done", models.BooleanField(default=False)),
                (
                    "tag",
                    models.ManyToManyField(related_name="tasks", to="todo_list.tag"),
                ),
            ],
            options={
                "ordering": ["is_done", "deadline"],
            },
        ),
    ]
